tunnel: 1b304a4e-dcc4-4145-a59b-da05876d926a
credentials-file: ./cloudflare/1b304a4e-dcc4-4145-a59b-da05876d926a.json

ingress:
  - hostname: dev.akshath.tech
    service: http://localhost:8001
  - service: http_status:404
